name: "Flatpak Builder"
description: "Build and create a bundle from a Flatpak manifest"
author: "Bilal Elmoussaoui"
branding:
  icon: "package"
  color: "blue"
inputs:
  manifest-path:
    description: "The relative path of the manifest file."
    required: true
  bundle:
    description: "The bundle name, by default it's app.flatpak"
    required: false
    default: "app.flatpak"
  repository-url:
    description: >
      The repository used to fetch the runtime when the user downloads the
      Flatpak bundle.
    required: false
    default: "https://flathub.org/repo/flathub.flatpakrepo"
  repository-name:
    description: >
      The repository name to install the runtime from at build/install time.
      Note that the repository name corresponds to the `repository-url` mentioned above.
    required: false
    default: "flathub"
  run-tests:
    description: >
      Toggles the run-tests config option on the defined flatpak-module.
      Possible values: true, enabled, yes, y. Or something else to disable them.
    default: "false"
    required: false
  gpg-homedir:
    description: >
      Path to the GPG home directory for looking up keyrings when signing build results.
      Only has an effect if `gpg-sign` is set.
    required: false
  gpg-sign:
    description: >
      The ID of a GPG key with which to sign the build results. Results will not be
      signed if this option is not set. The GPG key must be present in a keyring in
      the GPG home directory, which can be overridden using the `gpg-homedir` option.
    required: false
  cache:
    description: >
      Toggles caching the flatpak-builder directory.
      Possible values: true, enabled, yes, y. Or something else to disable it.
    default: "true"
    required: false
  cache-key:
    description: >
      Defines the cache-key to use.
      Defaults to flatpak-builder-${sha256(manifestPath)}
    required: false
  branch:
    description: The flatpak branch.
    default: "master"
    required: false
  arch:
    description: >
      The CPU architecture to build for.
    default: "x86_64"
    required: false
  mirror-screenshots-url:
    description: >
      The URL to mirror screenshots.
    required: false
runs:
  using: "node12"
  main: "dist/index.js"
